### ISSUE TITLE
Find Javascript RDF library

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-workflow-editor#1]
The library should be able to parse RDF in one of the formats that FREME supports and then query it. It does not need to be able to generate new RDF or query SPARQL endpoints.

**Comment by josauder** [comment]
The [javascript library](https://code.google.com/archive/p/rdfquery/) we started using seems to work for parsing xml.

I have troubles with querying but it should be possible to work this out.

**Comment by josauder** [comment]
I believe we can close this issue as rdfQuery fulfills our need and is able to parse rdf/xml.

Do you think we will have to revisit this issue when we add other RDF-Formats? If not, then close this

**Comment by jnehring** [comment]
It is ok when the program works internally with one RDF format only
