### ISSUE TITLE
dev version is broken

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-workflow-editor#22]
The [development version of the workflow editor](http://api-dev.freme-project.eu/freme-workflow-editor/) shows one javascruot error directly on startup:

```
annotation-handler.js:192 Uncaught SyntaxError: Unexpected token +
```

Then I load the HTML5 example, press "e-entity" and "enrich" and I get this error:

```
e-workflow.js:211 Uncaught ReferenceError: 
```

**Comment by ArneBinder** [comment]
@jnehring I can not reproduce this. Already fixed?

**Comment by jnehring** [comment]
I cannot reproduce the error also so I guess it is solved. [This error](https://github.com/freme-project/freme-workflow-editor/issues/23#issuecomment-222523090) that happens in the live version does not occur in the dev version.
