### ISSUE TITLE
Error with output simplification

### ISSUE THREAD

**Issue by fsasaki** [freme-project/freme-workflow-editor#27]
I get

> timestamp :1465376103447
> status :500
> error : Internal Server Error
> exception : eu.freme.common.exception.InternalServerErrorException
> message : No message available
> path : /toolbox/filter/documents/original-and-translation 

This happens after the pipeline, with the HTML input file provided as an example:
e-entity
e-terminology
e-translation

**Comment by jnehring** [comment]
This seems to be a problem in the backend. I opened https://github.com/freme-project/basic-services/issues/50

**Comment by jnehring** [comment]
In https://github.com/freme-project/basic-services/issues/50 we found out that the API endpoint has changed from "/toolbox/filter/documents/original-and-translation" to "/toolbox/convert/documents/original-and-translation". When the API endpoint has changed the FREME workflow editor has not been updated. This should be an easy bugfix.

**Comment by ArneBinder** [comment]
This is fixed, but the workflow from [above](https://github.com/freme-project/freme-workflow-editor/issues/27#issue-159112303) still does not work. e-Terminology produces no output.

**Comment by fsasaki** [comment]
Should we file a separate bug for e-Terminology?

**Comment by ArneBinder** [comment]
See [this](https://github.com/freme-project/freme-workflow-editor/issues/28). So I think we can close this.
